[gcp_service_account]
type = "service_account"
project_id = "potent-result-435708-u3"
private_key_id = "983e9fcc936c9be0c80a3cf13b4e3953f503901b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBr2b5kRsdQdu3
YbE0IlZA377ketFdt/qy60whh4kzUTzO7f0+Oivjy1ElYaaAcR0YfY20KSk5ubTl
LcGKaN90+gkFG+myhjVrcc73avuv/+JXFv+Q1iq1L5hlg2uJkyWo5pmaWA1MRrdp
7E6eiD3uTzBKKiSBZAPbvtDm1BnNqUWHktpV6g19ZXMjNA/kbjO4WCWsLx+ErL4x
4gNezQD4CAzpNMmds3WZKrXbeYIn3Z5ESP+m28AdXw0JKHdlbF2gwiauMI6N9Jf6
LRnMUW3qYwGMuG0hUkaHz+VT6yBlJQ2MegtEtajUyVq4R/zA5ajSNIiCt3DPJYUs
8CeiY+tlAgMBAAECggEACToD28uv0Pr8LoY23Nbt6PU/sL6xDpffF3riC47bWFh8
XxczQy2ePaHH4dH/DotU6X/Bql1zm05fcbN2TtOkIXxvxZCI13pRPScUxvCPwNid
vaxYzFuHeU4lImDaVJlv59XkZ1feek28Gw2oySCQYrPfBwlu58MN8//pD7X27LcY
Ukw24ZwTnQK1rRLmp7raIxqDY1y8N8nRuetSlrhfqPrCNxO2Pt4ybVP+2Fl2lAC4
0405s29kVW+uUa490vKWuRvHVseRVX3ntP4a7o0opQgxLivjzn3YhVK7Exwy3fHg
Pl8jEgu3WgkbkSQKRt1fIO6vga10PK8RomOzf0gYgQKBgQDxOdOd6bJlL5okXlKS
a8ceKelb+2oqOfPYqqhS8soN/gRndgsgLu46QdG2M4iOsbZ2eil88YGSMRl/syF3
+twFqvkwNWU0a1JFZdyQUTc1QFVK42p2bzd0jZXdYEYoPBnsvCWdDM/aPh9IhfJF
6cdiWYLdsRNdb7iJKWatg+F31QKBgQDNjC+kP14Yt4vIzQiLMgKbDc4xrNLEtKlb
TMGZ82T9CJNfw7ED6Wd7qsmmk76HGl8sr+EWvnJOU5bAOkQLnlpqWkY4WmFmgyCA
lso6tVBoCzxFeSpgxVIrGKCpLJxxgbSFpuOlY3TctnEyUdrDjtMAQXEuJq1EO5Ez
p0LNrWJ9UQKBgQDJ9pZcggsgeKhfhrEvchk2AfUlU+vhCsBESS3AtRHCgUiCruxF
t8Uw9WZ1W9QbVGLl8wXFXBYVphIpPnrpDxkjjbAwUqQ3LRumitAN7FGCvigrGRhL
rHYLmXc975sNmLRD5oq/YLitipF6kNr0+fQ7PaI5pkYGVsFz5TvYTrB5OQKBgERj
aRJ/1uHoZ8TWmwodCIroS/txIes6pMJwxlVfivE5YjdRl9rSVJDr4Q3gSFsRJitr
FTwI/2UaIKUyfaNT+4c5I/Xp9FA0PqMqCH0CCI+ldVc0Gip6XH1kQ0gmRKLrYdG6
FjHX5nDs7rqsS1oXchK6s1qEmc+C9iu2cd6W2pcRAoGAAKzD4IGiLfMxfh6VQBk0
HFtJmHnYXD66lnF8/XJh6pGCL4KjVMQTvIPNTpuDCDgHWucim/0AhuRQ3ftphl92
EHGlM1bbzVTp0qpTyq+pcJ8eSQm0kh5dIpc2+hNqGBRgBIgs914cwnAG0VMgG0TM
ZAHBKBpvUoP5ucN9r0G7GIg=
-----END PRIVATE KEY-----"""
client_email = "testing@potent-result-435708-u3.iam.gserviceaccount.com"
client_id = "115099754839300875479"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/testing%40potent-result-435708-u3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"